// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnboardingPlatform.Data.Implementations;

#nullable disable

namespace OnboardingPlatform.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnboardingPlatform.Core.Models.ConsentLog", b =>
                {
                    b.Property<Guid>("ConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConsentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("ConsentLogs");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CurrentAccountDetail", b =>
                {
                    b.Property<Guid>("CurrentAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CheckBookRequested")
                        .HasColumnType("bit");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("CustomerProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOpened")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrentAccountId");

                    b.HasIndex("CustomerProductId");

                    b.ToTable("CurrentAccountDetails");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerAddress", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAddresses");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerIdentifier", b =>
                {
                    b.Property<Guid>("IdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentifierValueHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentifierValueMasked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdentifierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdentifierType", "IdentifierValueHash")
                        .IsUnique();

                    b.ToTable("CustomerIdentifiers");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerProduct", b =>
                {
                    b.Property<Guid>("CustomerProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.ToTable("CustomerProducts");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.DraftApplication", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrimaryIdentifierType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryIdentifierValueHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecondaryIdentifierType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryIdentifierValueHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DraftId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("DraftApplications");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.PensionAccountDetail", b =>
                {
                    b.Property<Guid>("PensionAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContributionScheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateRegistered")
                        .HasColumnType("date");

                    b.Property<string>("EmployerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PfaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RsaPin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PensionAccountId");

                    b.HasIndex("CustomerProductId");

                    b.ToTable("PensionAccountDetails");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalFieldsSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredIdentifiers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-0001-0001-0001-aaaaaaaaaaaa"),
                            AdditionalFieldsSchema = "[\r\n  {\r\n    \"field\": \"branchPreference\",\r\n    \"label\": \"Preferred branch\",\r\n    \"type\": \"text\",\r\n    \"required\": false\r\n  }\r\n]",
                            CreatedAt = new DateTime(2026, 9, 15, 20, 15, 41, 44, DateTimeKind.Local).AddTicks(4010),
                            IsActive = true,
                            ProductCode = "SAVINGS",
                            ProductName = "Savings Account",
                            RequiredIdentifiers = "[\"BVN\"]"
                        },
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-0002-0002-0002-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 9, 15, 20, 15, 41, 44, DateTimeKind.Local).AddTicks(4016),
                            IsActive = true,
                            ProductCode = "CURRENT",
                            ProductName = "Current Account",
                            RequiredIdentifiers = "[\"BVN\"]"
                        },
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-0003-0003-0003-aaaaaaaaaaaa"),
                            AdditionalFieldsSchema = "[\r\n  {\r\n    \"field\": \"employerName\",\r\n    \"label\": \"Employer name\",\r\n    \"type\": \"text\",\r\n    \"required\": false\r\n  },\r\n  {\r\n    \"field\": \"contributionScheme\",\r\n    \"label\": \"Contribution scheme\",\r\n    \"type\": \"select\",\r\n    \"options\": [\r\n      \"MandatoryCPS\",\r\n      \"Voluntary\",\r\n      \"MicroPensionPlan\"\r\n    ],\r\n    \"required\": true\r\n  }\r\n]",
                            CreatedAt = new DateTime(2026, 9, 15, 20, 15, 41, 44, DateTimeKind.Local).AddTicks(4021),
                            IsActive = true,
                            ProductCode = "PENSION_RSA",
                            ProductName = "Pension (RSA)",
                            RequiredIdentifiers = "[\"NIN\",\"PHONE\"]"
                        },
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-0004-0004-0004-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 9, 15, 20, 15, 41, 44, DateTimeKind.Local).AddTicks(4037),
                            IsActive = true,
                            ProductCode = "STOCKBROKING",
                            ProductName = "Stockbroking",
                            RequiredIdentifiers = "[\"EMAIL\"]"
                        },
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-0005-0005-0005-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 9, 15, 20, 15, 41, 44, DateTimeKind.Local).AddTicks(4041),
                            IsActive = true,
                            ProductCode = "INSURANCE",
                            ProductName = "Insurance",
                            RequiredIdentifiers = "[\"EMAIL\",\"PHONE\"]"
                        });
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.SavingsAccountDetail", b =>
                {
                    b.Property<Guid>("SavingsAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("CustomerProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOpened")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SavingsAccountId");

                    b.HasIndex("CustomerProductId");

                    b.ToTable("SavingsAccountDetails");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.SecurityCheck", b =>
                {
                    b.Property<Guid>("SecurityCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SecurityCheckId");

                    b.HasIndex("DraftId");

                    b.ToTable("SecurityChecks");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.StockBrokingAccountDetail", b =>
                {
                    b.Property<Guid>("StockBrokingAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrokerageFirm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CscsNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CustomerProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOpened")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradingAccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StockBrokingAccountId");

                    b.HasIndex("CustomerProductId");

                    b.ToTable("StockBrokingAccountDetails");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.ConsentLog", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnboardingPlatform.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CurrentAccountDetail", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.CustomerProduct", "CustomerProduct")
                        .WithMany()
                        .HasForeignKey("CustomerProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProduct");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerAddress", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerIdentifier", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.Customer", "Customer")
                        .WithMany("Identifiers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerProduct", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.Customer", "Customer")
                        .WithMany("CustomerProducts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnboardingPlatform.Core.Models.Product", "Product")
                        .WithMany("CustomerProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.DraftApplication", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("OnboardingPlatform.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.PensionAccountDetail", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.CustomerProduct", "CustomerProduct")
                        .WithMany()
                        .HasForeignKey("CustomerProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProduct");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.SavingsAccountDetail", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.CustomerProduct", "CustomerProduct")
                        .WithMany()
                        .HasForeignKey("CustomerProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProduct");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.SecurityCheck", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.DraftApplication", "DraftApplication")
                        .WithMany()
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftApplication");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.StockBrokingAccountDetail", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.CustomerProduct", "CustomerProduct")
                        .WithMany()
                        .HasForeignKey("CustomerProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProduct");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CustomerProducts");

                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.Product", b =>
                {
                    b.Navigation("CustomerProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
