// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnboardingPlatform.Data.Implementations;

#nullable disable

namespace OnboardingPlatform.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnboardingPlatform.Core.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerAddress", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAddresses");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerIdentifier", b =>
                {
                    b.Property<Guid>("IdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentifierValueHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentifierValueMasked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdentifierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdentifierType", "IdentifierValueHash")
                        .IsUnique();

                    b.ToTable("CustomerIdentifiers");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerProduct", b =>
                {
                    b.Property<Guid>("CustomerProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.ToTable("CustomerProducts");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.DraftApplication", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrimaryIdentifierType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryIdentifierValueHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecondaryIdentifierType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryIdentifierValueHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DraftId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("DraftApplications");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalFieldsSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredIdentifiers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-0001-0001-0001-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 9, 14, 19, 4, 29, 713, DateTimeKind.Local).AddTicks(9623),
                            IsActive = true,
                            ProductCode = "SAVINGS",
                            ProductName = "Savings Account",
                            RequiredIdentifiers = "[\"BVN\"]"
                        },
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-0002-0002-0002-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 9, 14, 19, 4, 29, 713, DateTimeKind.Local).AddTicks(9638),
                            IsActive = true,
                            ProductCode = "CURRENT",
                            ProductName = "Current Account",
                            RequiredIdentifiers = "[\"BVN\"]"
                        },
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-0003-0003-0003-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 9, 14, 19, 4, 29, 713, DateTimeKind.Local).AddTicks(9643),
                            IsActive = true,
                            ProductCode = "PENSION_RSA",
                            ProductName = "Pension (RSA)",
                            RequiredIdentifiers = "[\"NIN\",\"PHONE\"]"
                        },
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-0004-0004-0004-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 9, 14, 19, 4, 29, 713, DateTimeKind.Local).AddTicks(9646),
                            IsActive = true,
                            ProductCode = "STOCKBROKING",
                            ProductName = "Stockbroking",
                            RequiredIdentifiers = "[\"EMAIL\"]"
                        },
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-0005-0005-0005-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 9, 14, 19, 4, 29, 713, DateTimeKind.Local).AddTicks(9649),
                            IsActive = true,
                            ProductCode = "INSURANCE",
                            ProductName = "Insurance",
                            RequiredIdentifiers = "[\"EMAIL\",\"PHONE\"]"
                        });
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerAddress", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerIdentifier", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.Customer", "Customer")
                        .WithMany("Identifiers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.CustomerProduct", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.Customer", "Customer")
                        .WithMany("CustomerProducts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnboardingPlatform.Core.Models.Product", "Product")
                        .WithMany("CustomerProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.DraftApplication", b =>
                {
                    b.HasOne("OnboardingPlatform.Core.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("OnboardingPlatform.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CustomerProducts");

                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("OnboardingPlatform.Core.Models.Product", b =>
                {
                    b.Navigation("CustomerProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
